"""Builds the ATLAS source bundle that docs/live/ runs in the visitor's browser.

    python scripts/build_live_bundle.py           # (re)write docs/live/atlas-bundle.zip + .json
    python scripts/build_live_bundle.py --check   # exit 1 if the bundle is stale

The "Run it live" page (docs/live/index.html) runs ATLAS's REAL code inside the
visitor's browser with Pyodide. It cannot import the repository, so it downloads
this zip: exactly the git-tracked source files ATLAS and the bank need, nothing
else -- no tests, no keys, no databases, no secrets.h, no atlas_ca.h.

Deterministic: files in sorted order, a fixed timestamp, line endings normalised to
LF, so the same source always gives the same zip on Windows and Linux. The
manifest (atlas-bundle.json) records every file's SHA-256, and
tests/test_live_bundle.py fails whenever a source file changed but the bundle was
not rebuilt -- the website can never quietly run older code than the repository.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import subprocess
import sys
import zipfile
from pathlib import Path

ATLAS_ROOT = Path(__file__).resolve().parent.parent
LIVE_DIR = ATLAS_ROOT / "docs" / "live"
BUNDLE = LIVE_DIR / "atlas-bundle.zip"
MANIFEST = LIVE_DIR / "atlas-bundle.json"

#: What the browser needs: the contracts, the keystore, ATLAS, the bank, the policies
#: (with their owner signatures and public keys), and the firmware's tested Python twin.
PATTERNS = ["contracts.py", "keystore.py", "atlas_service/*.py", "atlas_service/**/*.py",
            "atlas_service/policy/policies/*", "bank_service/*.py",
            "firmware/__init__.py", "firmware/virtual_device.py", "firmware/device_identity.py"]
#: Never shipped, whatever a pattern matches.
FORBIDDEN_SUFFIXES = (".key", ".db", ".pem", ".sqlite")
FORBIDDEN_NAMES = {"secrets.h", "atlas_ca.h", "tls-password.key"}
FIXED_TIME = (2026, 1, 1, 0, 0, 0)


def tracked_files() -> list[str]:
    out = subprocess.run(["git", "-C", str(ATLAS_ROOT), "ls-files", "--", *PATTERNS],
                         capture_output=True, text=True, check=True).stdout.split()
    files = sorted(set(out))
    bad = [f for f in files if f.endswith(FORBIDDEN_SUFFIXES) or Path(f).name in FORBIDDEN_NAMES]
    if bad:
        raise SystemExit(f"refusing to bundle secret-looking files: {bad}")
    return files


def normalised(rel: str) -> bytes:
    return (ATLAS_ROOT / rel).read_bytes().replace(b"\r\n", b"\n")


def build() -> tuple[bytes, dict]:
    files = tracked_files()
    manifest = {"files": {}, "note": "generated by scripts/build_live_bundle.py -- do not edit"}
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for rel in files:
            data = normalised(rel)
            info = zipfile.ZipInfo(rel, FIXED_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            z.writestr(info, data)
            manifest["files"][rel] = hashlib.sha256(data).hexdigest()
    blob = buf.getvalue()
    manifest["bundle_sha256"] = hashlib.sha256(blob).hexdigest()
    manifest["file_count"] = len(files)
    return blob, manifest


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if docs/live/ is stale")
    args = ap.parse_args(argv)
    blob, manifest = build()
    if args.check:
        current = json.loads(MANIFEST.read_text(encoding="utf-8")) if MANIFEST.exists() else {}
        fresh = BUNDLE.exists() and BUNDLE.read_bytes() == blob and current == manifest
        print("[live-bundle] up to date" if fresh else
              "[live-bundle] STALE -- run: python scripts/build_live_bundle.py")
        return 0 if fresh else 1
    LIVE_DIR.mkdir(parents=True, exist_ok=True)
    BUNDLE.write_bytes(blob)
    MANIFEST.write_text(json.dumps(manifest, indent=1, sort_keys=True) + "\n", encoding="utf-8", newline="\n")
    print(f"[live-bundle] wrote {BUNDLE.relative_to(ATLAS_ROOT)}: {manifest['file_count']} files, "
          f"{len(blob):,} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
