"""Builds the ATLAS source bundle that docs/live/ runs in the visitor's browser.

    python scripts/build_live_bundle.py           # (re)write docs/live/atlas-bundle.zip + .json
    python scripts/build_live_bundle.py --check   # exit 1 if the bundle is stale

The "Run it live" page (docs/live/index.html) runs ATLAS's REAL code inside the
visitor's browser with Pyodide. It cannot import the repository, so it downloads
this zip: exactly the git-tracked source files ATLAS and the bank need, nothing
else -- no tests, no keys, no databases, no secrets.h, no atlas_ca.h.

Reproducible: files in sorted order, a fixed timestamp, a fixed "made on" system
marker and line endings normalised to LF. The manifest (atlas-bundle.json) records
every file's SHA-256 and the zip's own SHA-256 (which the page checks before running
anything). --check compares CONTENTS, not zip bytes -- different machines' compressors
may encode the same files differently (found 2026-10-02: a Linux rebuild differed from
the Windows one byte-wise, file-for-file identical) -- and fails whenever a source file
changed but the bundle was not rebuilt, so the website can never quietly run older
code than the repository.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import subprocess
import sys
import zipfile
from pathlib import Path

ATLAS_ROOT = Path(__file__).resolve().parent.parent
LIVE_DIR = ATLAS_ROOT / "docs" / "live"
BUNDLE = LIVE_DIR / "atlas-bundle.zip"
MANIFEST = LIVE_DIR / "atlas-bundle.json"

#: What the browser needs: the contracts, the keystore, ATLAS, the bank, the policies
#: (with their owner signatures and public keys), and the firmware's tested Python twin.
PATTERNS = ["contracts.py", "keystore.py", "atlas_service/*.py", "atlas_service/**/*.py",
            "atlas_service/policy/policies/*", "bank_service/*.py",
            "firmware/__init__.py", "firmware/virtual_device.py", "firmware/device_identity.py"]
#: Never shipped, whatever a pattern matches.
FORBIDDEN_SUFFIXES = (".key", ".db", ".pem", ".sqlite")
FORBIDDEN_NAMES = {"secrets.h", "atlas_ca.h", "tls-password.key"}
FIXED_TIME = (2026, 1, 1, 0, 0, 0)


def tracked_files() -> list[str]:
    out = subprocess.run(["git", "-C", str(ATLAS_ROOT), "ls-files", "--", *PATTERNS],
                         capture_output=True, text=True, check=True).stdout.split()
    files = sorted(set(out))
    bad = [f for f in files if f.endswith(FORBIDDEN_SUFFIXES) or Path(f).name in FORBIDDEN_NAMES]
    if bad:
        raise SystemExit(f"refusing to bundle secret-looking files: {bad}")
    return files


def normalised(rel: str) -> bytes:
    return (ATLAS_ROOT / rel).read_bytes().replace(b"\r\n", b"\n")


def build() -> tuple[bytes, dict]:
    files = tracked_files()
    manifest = {"files": {}, "note": "generated by scripts/build_live_bundle.py -- do not edit"}
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for rel in files:
            data = normalised(rel)
            info = zipfile.ZipInfo(rel, FIXED_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            info.create_system = 3                  # zipfile otherwise records the building OS
            z.writestr(info, data)
            manifest["files"][rel] = hashlib.sha256(data).hexdigest()
    blob = buf.getvalue()
    manifest["bundle_sha256"] = hashlib.sha256(blob).hexdigest()
    manifest["file_count"] = len(files)
    return blob, manifest


def check(bundle: Path = BUNDLE, manifest_path: Path = MANIFEST) -> list[str]:
    """Why docs/live is stale or inconsistent; empty when it is current. Compares the
    current source, the manifest and the committed zip by content."""
    expected = {rel: hashlib.sha256(normalised(rel)).hexdigest() for rel in tracked_files()}
    if not manifest_path.exists() or not bundle.exists():
        return ["docs/live/atlas-bundle.zip or .json is missing"]
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    problems = []
    changed = sorted(set(expected.items()) ^ set(manifest.get("files", {}).items()))
    if changed:
        problems.append("source differs from the manifest: " + ", ".join(sorted({rel for rel, _ in changed}))[:300])
    if manifest.get("file_count") != len(expected):
        problems.append(f"manifest counts {manifest.get('file_count')} files, the source has {len(expected)}")
    blob = bundle.read_bytes()
    if hashlib.sha256(blob).hexdigest() != manifest.get("bundle_sha256"):
        problems.append("the zip does not match the manifest's bundle_sha256 (the page would refuse it)")
    with zipfile.ZipFile(io.BytesIO(blob)) as z:
        if z.namelist() != sorted(expected):
            problems.append("the zip's file list differs from the source")
        else:
            bad = [n for n in z.namelist() if hashlib.sha256(z.read(n)).hexdigest() != expected[n]]
            if bad:
                problems.append("zip members differ from the source: " + ", ".join(bad)[:300])
    return problems


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if docs/live/ is stale")
    args = ap.parse_args(argv)
    if args.check:
        problems = check()
        for problem in problems:
            print(f"[live-bundle] {problem}")
        print("[live-bundle] up to date" if not problems else
              "[live-bundle] STALE -- run: python scripts/build_live_bundle.py")
        return 0 if not problems else 1
    blob, manifest = build()
    LIVE_DIR.mkdir(parents=True, exist_ok=True)
    BUNDLE.write_bytes(blob)
    MANIFEST.write_text(json.dumps(manifest, indent=1, sort_keys=True) + "\n", encoding="utf-8", newline="\n")
    print(f"[live-bundle] wrote {BUNDLE.relative_to(ATLAS_ROOT)}: {manifest['file_count']} files, "
          f"{len(blob):,} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
