"""ATLAS's own ML layer on REAL bank customers: how often it raises a false alarm.

    python scripts/evaluate_real_data.py             # needs the dataset below, once
    python scripts/evaluate_real_data.py --json

WHY. Everything else ATLAS measures about its ML runs on customers generated by
atlas_service/ml/synth.py -- the same code that trained the model -- so it shows
separation on generated data. This script feeds REAL people's payments through
the very same per-customer Isolation Forest, banding rule and burst signal.

DATASET. PKDD'99 Discovery Challenge "Financial" data (Petr Berka and Marta
Sochorova): the real, anonymised transactions of 4,500 accounts of a Czech bank,
1993-1998, released by the bank for research. Read from the tab-separated copy
at github.com/dnoeth/1999_Czech_financial_dataset_Teradata (fin_trans.tsv, which
adds 20 years to every date and divides amounts by 10 -- neither changes a
per-customer comparison). No source states a licence; the file is kept in
~/.atlas/datasets/pkdd99 -- outside the repository and OneDrive -- and never
committed. Only the aggregate figures below are written, to
docs/ml-real-data.json.

WHAT IS MEASURED -- and what is not. The data has no fraud labels, so every
payment in it is treated as what it almost certainly is: an ordinary payment by
its real owner. That measures FALSE ALARMS on real behaviour -- how often ATLAS
would bother a genuine customer -- and nothing about catching fraud.

  * A payment is a customer-initiated debit: a cash withdrawal, a card payment,
    or a transfer to another bank (whose partner bank + account is the payee).
    The bank's own charges (statement fees ST, penalty interest IO) are left
    out: the customer did not choose to make them.
  * The data has dates but no times, so every payment is placed at 12:00 and the
    hour-of-day feature is constant. Device, location and the international,
    travel and emergency flags are constant too (one bank, one country). The
    features that DO vary are the ones that carry most of the signal: amount
    relative to the customer's own history, a new payee, a new payment category,
    and payments in the last 24 hours.
  * Method, fixed before running: every account with at least 250 payments.
    The test payments are each account's 201st to 250th. For a history size H
    in (50, 100, 150, 200), the model is fitted on the H payments immediately
    before the test window -- exactly how ATLAS fits a customer -- and each test
    payment is scored against ALL of that customer's earlier payments, as the
    live service does. The same test payments are used for every H, so the only
    thing that changes between rows is how much history the model learned from.
  * Reported per H: the share of test payments banded MEDIUM or HIGH, the share
    banded HIGH (the level user-demo-1's high_ml_risk rule acts on), and the
    share on which the beyond_observed_range burst signal fires. Pooled over all
    test payments, with the spread across accounts.

Deterministic: the Isolation Forest's random_state is fixed, and the account
selection and windows depend only on the data.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

ATLAS_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ATLAS_ROOT))

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

DATA = Path.home() / ".atlas" / "datasets" / "pkdd99" / "fin_trans.tsv"
OUT = ATLAS_ROOT / "docs" / "ml-real-data.json"
SOURCE_URL = "https://github.com/dnoeth/1999_Czech_financial_dataset_Teradata"
HISTORY_SIZES = (50, 100, 150, 200)
TEST_START, TEST_END = 200, 250           # the 201st to 250th payment
BANK_CHARGES = {"ST", "IO"}               # statement fees, penalty interest
COLUMNS = ["trans_id", "account", "date", "amount", "balance", "type", "operation",
           "k_symbol", "bank", "partner"]


def payments_by_account(path: Path) -> dict[str, list[dict]]:
    """Customer-initiated debits, per account, oldest first."""
    accounts: dict[str, list[dict]] = {}
    with path.open(encoding="utf-8") as f:
        for line in f:
            row = dict(zip(COLUMNS, line.rstrip("\n").split("\t")))
            if row.get("type") not in ("D", "P"):
                continue
            if row.get("k_symbol", "").strip() in BANK_CHARGES:
                continue
            accounts.setdefault(row["account"], []).append(row)
    for rows in accounts.values():
        rows.sort(key=lambda r: (r["date"], int(r["trans_id"])))
    return accounts


def to_transaction(row: dict, subject: str):
    """One real payment in ATLAS's own Transaction contract."""
    from contracts import Transaction

    partner = (row.get("bank", "").strip() + ":" + row.get("partner", "").strip()).strip(":")
    operation = row.get("operation", "").strip()
    if operation == "ROB" and partner:
        beneficiary = f"acct-{partner}"
    elif operation == "CCW":
        beneficiary = "card-payment"
    else:
        beneficiary = "cash-withdrawal"
    category = row.get("k_symbol", "").strip() or {"ROB": "transfer", "CCW": "card"}.get(operation, "cash")
    return Transaction(
        transaction_id=f"pkdd-{row['trans_id']}", subject=subject,
        amount=f"{float(row['amount']):.2f}", currency="CZK", beneficiary=beneficiary,
        location="CZ", device_id="branch", merchant_category=category,
        authentication_method="bank", timestamp=f"{row['date']}T12:00:00+00:00",
    )


def _bands(model, test, history_all):
    """PersonaAnomalyModel.score(), batched: the same features, scaler, forest and
    percentile banding, for many payments at once. Cross-checked against score()
    on every account (see evaluate)."""
    from atlas_service.ml.features import extract_features

    vectors = np.array([extract_features(t, h) for t, h in zip(test, history_all)])
    raw = -model._model.decision_function(model._scaler.transform(vectors))
    p90, p98 = np.percentile(model._train_scores, [90, 98])
    return ["HIGH" if s >= p98 else "MEDIUM" if s >= p90 else "LOW" for s in raw]


def evaluate(path: Path = DATA, progress=print) -> dict:
    from atlas_service.ml import range_signal as rs
    from atlas_service.ml.model import PersonaAnomalyModel

    started = time.perf_counter()
    accounts = payments_by_account(path)
    eligible = sorted((a for a, rows in accounts.items() if len(rows) >= TEST_END), key=int)
    progress(f"[real-data] {len(accounts)} accounts with payments; {len(eligible)} have at least {TEST_END}")

    per_h = {h: {"medium_or_high": 0, "high": 0, "accounts_medium_or_high": [], "accounts_high": []}
             for h in HISTORY_SIZES}
    signal_fired = 0
    tested = 0
    for n, account in enumerate(eligible, start=1):
        txs = [to_transaction(r, f"cz-{account}") for r in accounts[account][:TEST_END]]
        test = txs[TEST_START:TEST_END]
        prior = [txs[:TEST_START + i] for i in range(len(test))]
        tested += len(test)
        for t, h in zip(test, prior):
            signal_fired += rs.fires(*rs.measure(t, h), rs.RANGE_MULTIPLIER)
        for size in HISTORY_SIZES:
            model = PersonaAnomalyModel().fit(txs[TEST_START - size:TEST_START])
            bands = _bands(model, test, prior)
            if n <= 3 and size == HISTORY_SIZES[-1]:           # the batch equals score()
                assert bands[:5] == [model.score(t, h).risk_band for t, h in zip(test[:5], prior[:5])]
            mh = sum(b != "LOW" for b in bands)
            hi = sum(b == "HIGH" for b in bands)
            per_h[size]["medium_or_high"] += mh
            per_h[size]["high"] += hi
            per_h[size]["accounts_medium_or_high"].append(mh / len(test))
            per_h[size]["accounts_high"].append(hi / len(test))
        if n % 100 == 0:
            progress(f"[real-data] {n}/{len(eligible)} accounts")

    def spread(values):
        q = np.percentile(values, [25, 50, 75, 90])
        return {"p25": round(float(q[0]), 4), "median": round(float(q[1]), 4),
                "p75": round(float(q[2]), 4), "p90": round(float(q[3]), 4)}

    rows = []
    for size in HISTORY_SIZES:
        r = per_h[size]
        rows.append({
            "history_size": size,
            "medium_or_high": r["medium_or_high"],
            "high": r["high"],
            "medium_or_high_rate": round(r["medium_or_high"] / tested, 4),
            "high_rate": round(r["high"] / tested, 4),
            "per_account_medium_or_high": spread(r["accounts_medium_or_high"]),
            "per_account_high": spread(r["accounts_high"]),
        })
    return {
        "method": "measured by scripts/evaluate_real_data.py",
        "measured_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "dataset": {
            "name": "PKDD'99 Discovery Challenge financial data (Czech bank, 1993-1998)",
            "source": SOURCE_URL,
            "real": True, "fraud_labels": False, "committed": False,
        },
        "what_it_measures": "false alarms on real customers' ordinary payments; not fraud detection",
        "constant_features": ["hour_of_day", "is_new_device", "is_new_location", "is_international",
                              "declared_travel_mode", "is_emergency_request"],
        "accounts": len(eligible),
        "test_payments": tested,
        "test_window": f"each account's payments {TEST_START + 1}-{TEST_END}",
        "by_history_size": rows,
        "burst_signal": {"multiplier": rs.RANGE_MULTIPLIER, "fired": signal_fired,
                         "rate": round(signal_fired / tested, 4)},
        "seconds": round(time.perf_counter() - started, 1),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--json", action="store_true", help="print the result as JSON")
    args = ap.parse_args()
    if not DATA.exists():
        print(f"[real-data] {DATA} is missing. Download fin_trans.tsv from {SOURCE_URL} into that folder.")
        return 2
    result = evaluate()
    OUT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(f"[real-data] {result['accounts']} real accounts, {result['test_payments']} test payments")
        for r in result["by_history_size"]:
            print(f"  history {r['history_size']:>3}: MEDIUM or HIGH {r['medium_or_high']} "
                  f"({r['medium_or_high_rate']:.1%}), HIGH {r['high']} ({r['high_rate']:.2%})")
        b = result["burst_signal"]
        print(f"  burst signal fired on {b['fired']} of {result['test_payments']} ({b['rate']:.2%})")
        print(f"[real-data] wrote {OUT.relative_to(ATLAS_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
